/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel.User;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Hotel.Login.SambungDatabase;
public class UserCetakTransaksi extends javax.swing.JFrame {
    SambungDatabase DB = new SambungDatabase();
    ResultSet rs;
    int ID;
    String NAMA;
    String EMAIL;

    public UserCetakTransaksi(int iid) {
        initComponents();
        setLocationRelativeTo(null);
        this.ID = iid;

        try {
            String KodeSQL = "SELECT * FROM Transaksi WHERE id=" + ID + ";";
            rs = DB.STATMENT().executeQuery(KodeSQL);
            rs.next();
            NAMA = rs.getString("nama");
            EMAIL = rs.getString("email");
            id.setText("Invoice No #" + rs.getString("id"));
            nama.setText(rs.getString("nama"));
            email.setText(rs.getString("email"));
            cekin.setText(rs.getString("tgl_cekin"));
            cekout.setText(rs.getString("tgl_cekout"));
            jenis_kamar.setText(rs.getString("jenis_kamar"));
            harga_permalam.setText(rs.getString("harga_permalam"));
            lantai.setText(rs.getString("lantai_kamar"));
            fasilitas.setText(rs.getString("fasilitas"));
            total_harga.setText("Rp" + rs.getString("total_harga"));

        } catch (SQLException x) {
            System.out.println("Eror : " + x);
        }

        NamaUser.setText(NAMA);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kembali = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fasilitas = new javax.swing.JLabel();
        cekout = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cekin = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        total_harga = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jenis_kamar = new javax.swing.JLabel();
        harga_permalam = new javax.swing.JLabel();
        lantai = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NamaUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(590, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("<< Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(12, 13, 71, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), null));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("OYO Reservasi");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 20, 190, 28);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INVOICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(-30, 0, 520, 60);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Oyo Reservasi, JL. Lembus, Samarinda Ulu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel26)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 500, 520, 30);

        id.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        id.setText("Invoice No #");
        jPanel3.add(id);
        id.setBounds(320, 80, 140, 17);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Cek Out:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(330, 190, 60, 14);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Email");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(60, 150, 60, 15);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText(":");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(120, 150, 10, 15);

        email.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        email.setText("-");
        jPanel3.add(email);
        email.setBounds(150, 150, 220, 15);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText(":");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(240, 370, 20, 15);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel12.setText("Nama ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(60, 130, 60, 15);

        fasilitas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        fasilitas.setText("-");
        jPanel3.add(fasilitas);
        fasilitas.setBounds(280, 370, 210, 15);

        cekout.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cekout.setText("-");
        jPanel3.add(cekout);
        cekout.setBounds(330, 210, 140, 14);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel14.setText("Harga Permalam");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(140, 310, 110, 14);

        cekin.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cekin.setText("-");
        jPanel3.add(cekin);
        cekin.setBounds(120, 210, 150, 14);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel16.setText("Cek In :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(130, 190, 60, 14);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel17.setText("Jenis Kamar");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(140, 280, 120, 14);

        total_harga.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        total_harga.setText("RP 1200000");
        jPanel3.add(total_harga);
        total_harga.setBounds(310, 450, 120, 20);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel19.setText("Lantai");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(140, 340, 110, 14);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel20.setText(":");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(120, 130, 10, 15);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel21.setText(":");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(240, 280, 20, 15);

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel22.setText(":");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(240, 310, 20, 15);

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel23.setText(":");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(240, 340, 20, 15);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel24.setText("Vasilitas");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(140, 370, 110, 14);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel25.setText("INVOICE TOTAL");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(300, 420, 140, 20);

        nama.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        nama.setText("-");
        jPanel3.add(nama);
        nama.setBounds(150, 130, 270, 15);

        jenis_kamar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jenis_kamar.setText("-");
        jPanel3.add(jenis_kamar);
        jenis_kamar.setBounds(280, 280, 210, 15);

        harga_permalam.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        harga_permalam.setText("-");
        jPanel3.add(harga_permalam);
        harga_permalam.setBounds(280, 310, 210, 15);

        lantai.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lantai.setText("-");
        jPanel3.add(lantai);
        lantai.setBounds(280, 340, 210, 15);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(66, 40, 460, 524);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 670, 620);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        NamaUser.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        NamaUser.setForeground(new java.awt.Color(255, 51, 51));
        NamaUser.setText("Nama User");
        jPanel2.add(NamaUser);
        NamaUser.setBounds(390, 0, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/pict/oyo.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 0, 80, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/pict/user.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 0, 34, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        this.setVisible(false);
        new userTransaksi(EMAIL).setVisible(true);
    }//GEN-LAST:event_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCetakTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCetakTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCetakTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCetakTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCetakTransaksi(9).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NamaUser;
    private javax.swing.JLabel cekin;
    private javax.swing.JLabel cekout;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fasilitas;
    private javax.swing.JLabel harga_permalam;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jenis_kamar;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel lantai;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel total_harga;
    // End of variables declaration//GEN-END:variables
}
