/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel.Menu;

import Hotel.Admin.HalamanAdmin;
import Hotel.Login.SambungDatabase;

import java.awt.HeadlessException;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class CrudTransaksi extends javax.swing.JFrame implements interfaceTable, interfaceCRUD {

    SambungDatabase DB = new SambungDatabase();
    boolean status;
    DefaultTableModel model;

    ResultSet rs;
    String KodeSQL, CEKIN, CEKOUT, SEKARANG;
    Transaksi TRAN = new Transaksi();
    long lama, pilihTanggal1 ;
    int a = 0, b = 0;

    public CrudTransaksi() {
        initComponents();
        setLocationRelativeTo(null);

        String[] judul
                = {"ID",
                    "Nama",
                    "Email",
                    "Cekin",
                    "Cekout",
                    "Jenis Kamar",
                    "Lantai",
                    "Harga Permalam",
                    "Fasilitas",
                    "Total Harga"};
        model = new DefaultTableModel(judul, 0);
        tabel.setModel(model);
        tampilkanTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_total_harga = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        fasilitas = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        harga_permalam = new javax.swing.JTextField();
        lantai_kamar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        total_harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tgl_cekout = new com.toedter.calendar.JDateChooser();
        tgl_cekin = new com.toedter.calendar.JDateChooser();
        jenis_kamar = new javax.swing.JComboBox<>();
        jumlah_hari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        KolomFasilitas2 = new javax.swing.JLabel();
        titel = new javax.swing.JLabel();
        KolomFasilitas1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 800));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CRUD Transaksi");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 0, 190, 28);

        kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("<< Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(30, 10, 71, 17);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Email", "Cek-In", "Cek-Out", "Jenis Kamar", "Lantai", "Harga/malam", "Fasilitas", "Total Harga"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setMinWidth(5);
            tabel.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabel.getColumnModel().getColumn(0).setMaxWidth(5);
            tabel.getColumnModel().getColumn(6).setPreferredWidth(20);
            tabel.getColumnModel().getColumn(6).setMaxWidth(20);
            tabel.getColumnModel().getColumn(7).setPreferredWidth(60);
            tabel.getColumnModel().getColumn(7).setMaxWidth(60);
            tabel.getColumnModel().getColumn(8).setPreferredWidth(30);
            tabel.getColumnModel().getColumn(8).setMaxWidth(30);
            tabel.getColumnModel().getColumn(9).setPreferredWidth(50);
            tabel.getColumnModel().getColumn(9).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 370, 820, 190);

        btn_total_harga.setBackground(new java.awt.Color(255, 255, 48));
        btn_total_harga.setText("Hitung Total");
        btn_total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_total_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_total_harga);
        btn_total_harga.setBounds(730, 200, 120, 30);

        btn_hapus.setBackground(new java.awt.Color(250, 86, 77));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus);
        btn_hapus.setBounds(660, 570, 190, 23);

        fasilitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "VIP    (+100000)", "VVIP  (+200000)" }));
        fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fasilitasActionPerformed(evt);
            }
        });
        jPanel1.add(fasilitas);
        fasilitas.setBounds(570, 160, 280, 30);

        btn_tambah.setBackground(new java.awt.Color(77, 250, 152));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah);
        btn_tambah.setBounds(250, 340, 600, 23);

        btn_reset.setBackground(new java.awt.Color(255, 255, 204));
        btn_reset.setText("Reset Form");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset);
        btn_reset.setBounds(30, 340, 190, 23);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Harga Permalam");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 120, 79, 30);

        harga_permalam.setEditable(false);
        harga_permalam.setMinimumSize(new java.awt.Dimension(8, 20));
        jPanel1.add(harga_permalam);
        harga_permalam.setBounds(570, 120, 280, 30);

        lantai_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7" }));
        lantai_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lantai_kamarActionPerformed(evt);
            }
        });
        jPanel1.add(lantai_kamar);
        lantai_kamar.setBounds(570, 80, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setText("Lantai Kamar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 80, 62, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setText("ID ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 40, 42, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel8.setText("Tanggal Cek-In");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 160, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setText("Tanggal Cek-Out");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 200, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel10.setText("Total Harga");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 200, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Kamar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 40, 57, 30);

        id.setEditable(false);
        jPanel1.add(id);
        id.setBounds(120, 40, 280, 30);

        total_harga.setEditable(false);
        jPanel1.add(total_harga);
        total_harga.setBounds(570, 200, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel11.setText("Nama");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 80, 42, 30);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 120, 42, 30);
        jPanel1.add(nama);
        nama.setBounds(120, 80, 280, 30);
        jPanel1.add(email);
        email.setBounds(120, 120, 280, 30);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel13.setText("Fasilitas");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(480, 160, 70, 30);
        jPanel1.add(tgl_cekout);
        tgl_cekout.setBounds(120, 200, 210, 30);
        jPanel1.add(tgl_cekin);
        tgl_cekin.setBounds(120, 160, 210, 30);

        jenis_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Standar", "Supperior", "Deluxe", "Suite", "Presidential Suite" }));
        jenis_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kamarActionPerformed(evt);
            }
        });
        jPanel1.add(jenis_kamar);
        jenis_kamar.setBounds(570, 40, 280, 30);

        jumlah_hari.setEditable(false);
        jumlah_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_hariActionPerformed(evt);
            }
        });
        jPanel1.add(jumlah_hari);
        jumlah_hari.setBounds(340, 200, 60, 30);

        jLabel1.setText("Jumlah Hari");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 160, 80, 40);

        btn_ubah.setBackground(new java.awt.Color(255, 255, 48));
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah);
        btn_ubah.setBounds(30, 570, 190, 23);

        KolomFasilitas2.setText("-");
        jPanel1.add(KolomFasilitas2);
        KolomFasilitas2.setBounds(30, 310, 820, 14);

        titel.setText("Fasilitas :");
        jPanel1.add(titel);
        titel.setBounds(30, 250, 70, 14);

        KolomFasilitas1.setText("-");
        jPanel1.add(KolomFasilitas1);
        KolomFasilitas1.setBounds(30, 280, 820, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CREATE() {
        try {
            if ("".equals(total_harga.getText())) {
                JOptionPane.showMessageDialog(this, "Lihat Total Dulu weyyy", "Pesan", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    String cekin = new SimpleDateFormat("dd-MM-yyyy").format(tgl_cekin.getDate());
                    String cekout = new SimpleDateFormat("dd-MM-yyyy").format(tgl_cekout.getDate());

                    TRAN.setNama(nama.getText());
                    TRAN.setEmail(email.getText());
                    TRAN.setTgl_cekin(cekin);
                    TRAN.setTgl_cekout(cekout);
                    TRAN.setTotal_harga(Integer.parseInt(total_harga.getText()));
                    TRAN.setHarga_permalam(Integer.parseInt(harga_permalam.getText()));

                    DB.STATMENT().executeUpdate("INSERT INTO Transaksi VALUES"
                            + "(NULL, '" + TRAN.getNama() + "','" + TRAN.getEmail() + "','" + TRAN.getTgl_cekin() + "','" + TRAN.getTgl_cekout() + "','"
                            + TRAN.getJenis_kamar() + "'," + TRAN.getLantai_kamar() + "," + TRAN.getHarga_permalam() + ",'"
                            + TRAN.getFasilitas() + "'," + TRAN.getTotal_harga() + ")");

                    tampilkanTabel();
                    reset();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah!");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "ID Sudah Tersedia");
                }
            }
        } catch (HeadlessException e) {
            System.out.println("eror : " + e);
        }
    }

    public void DELETE() {
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus data ini ?");
        switch (opsi) {
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                try {
                    DB.STATMENT().executeUpdate("DELETE FROM Transaksi WHERE id='" + id.getText() + "'");
                    tampilkanTabel();
                    reset();
                } catch (SQLException ex) {

                }
                break;
            default:
                break;
        }
    }

    public void UPDATE() {
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin Mengubah data ini ?");
        switch (opsi) {
            case JOptionPane.YES_OPTION:
               
                try {
                if ("".equals(total_harga.getText())) {
                    JOptionPane.showMessageDialog(this, "Di Total Kan Dulu weyyy", "Pesan", JOptionPane.WARNING_MESSAGE);
                } else {
                    try {
                        String cekin = new SimpleDateFormat("dd-MM-yyyy").format(tgl_cekin.getDate());
                        String cekout = new SimpleDateFormat("dd-MM-yyyy").format(tgl_cekout.getDate());

                        TRAN.setId_transaksi(Integer.parseInt(id.getText()));
                        TRAN.setNama(nama.getText());
                        TRAN.setEmail(email.getText());
                        TRAN.setTgl_cekin(cekin);
                        TRAN.setTgl_cekout(cekout);
                        TRAN.setTotal_harga(Integer.parseInt(total_harga.getText()));
                        TRAN.setHarga_permalam(Integer.parseInt(harga_permalam.getText()));

                        DB.STATMENT().executeUpdate("UPDATE Transaksi SET nama = '" + TRAN.getNama()
                                + "', email = '" + TRAN.getEmail() + "', tgl_cekin = '" + TRAN.getTgl_cekin() + "', tgl_cekout = '"
                                + TRAN.getTgl_cekout() + "', jenis_kamar = '" + TRAN.getJenis_kamar() + "', lantai_kamar = '" + TRAN.getLantai_kamar() + "', harga_permalam = '" + TRAN.getHarga_permalam() + "', total_harga = '"
                                + TRAN.getTotal_harga() + "' WHERE id = '" + TRAN.getId_transaksi() + "';");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
                        tampilkanTabel();
                        reset();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "ID Sudah Tersedia");
                    }
                }
            } catch (HeadlessException e) {
                System.out.println("eror : " + e);
            }
            break;
            default:
                break;
        }
    }

    public void reset() {
        id.setText("");
        nama.setText("");
        email.setText("");
        tgl_cekin.setDate(null);
        tgl_cekout.setDate(null);
        jenis_kamar.setSelectedIndex(0);
        lantai_kamar.setSelectedIndex(0);
        fasilitas.setSelectedIndex(0);
        harga_permalam.setText("");
        total_harga.setText("");
        jumlah_hari.setText("");
    }


    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        CREATE();

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_total_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_total_hargaActionPerformed
        try {
            if ("".equals(nama.getText())
                    || "".equals(email.getText().toLowerCase())
                    || tgl_cekin.getDate() == null
                    || tgl_cekout.getDate() == null
                    || "".equals(TRAN.getJenis_kamar())
                    || TRAN.getLantai_kamar() == 0) {
                JOptionPane.showMessageDialog(this, "Mohon isi seluruh data !!", "Pesan", JOptionPane.WARNING_MESSAGE);

            } else {
                Date sekarang = new Date();
                SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
                CEKIN = FormatTanggal.format(tgl_cekin.getDate());
                CEKOUT = FormatTanggal.format(tgl_cekout.getDate());
                SEKARANG = FormatTanggal.format(sekarang);

                try {

                    DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
                    Date tanggalcekin = format.parse(CEKIN);
                    Date tanggalcekout = format.parse(CEKOUT);
                    Date tanggalsekarang = format.parse(SEKARANG);

                    long tanggalcekin1 = tanggalcekin.getTime();
                    long tanggalcekout1 = tanggalcekout.getTime();
                    long tanggalsekarang1 = tanggalsekarang.getTime();
                    long pilihTanggal = tanggalcekin1 - tanggalsekarang1;
                    long diff = tanggalcekout1 - tanggalcekin1;

                    lama          = diff / (24 * 60 * 60 * 1000);
                    pilihTanggal1 = pilihTanggal / (24 * 60 * 60 * 1000);

                } catch (ParseException e) {
                    System.out.println("" + e.getMessage());
                }

                if (lama > 0 && pilihTanggal1 >= 0) {
                    jumlah_hari.setText(Long.toString(lama));
                    int c = Integer.parseInt(jumlah_hari.getText());
                    total_harga.setText(String.valueOf((a + b) * c));
                } else {
                    JOptionPane.showMessageDialog(this, "Masukan Tanggal dengan Benar !", "Pesan", JOptionPane.WARNING_MESSAGE);
                }

            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Masukan Data dengan Benar !", "Pesan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_total_hargaActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        DELETE();

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int i = tabel.getSelectedRow();
        if (i > -1) {
            id.setText(model.getValueAt(i, 0).toString());
            nama.setText(model.getValueAt(i, 1).toString());
            email.setText(model.getValueAt(i, 2).toString());
//            tgl_cekin.setDate(model.getValueAt(i, 3).toString());
//            tgl_cekout.setDate(model.getValueAt(i, 4).toString());
            jenis_kamar.setSelectedItem(model.getValueAt(i, 5).toString());
            lantai_kamar.setSelectedItem(model.getValueAt(i, 6).toString());
            harga_permalam.setText(model.getValueAt(i, 7).toString());
            fasilitas.setSelectedItem(model.getValueAt(i, 8).toString());
            total_harga.setText(model.getValueAt(i, 9).toString());

        }
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void fasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fasilitasActionPerformed
        switch (fasilitas.getSelectedIndex()) {
            case 0:
                b = 0;
                TRAN.setFasilitas("Default");
                KolomFasilitas1.setText("- AC     - 2 Bed     - 1 Kamar mandi     - 2 buah bedside cabinet ");
                KolomFasilitas2.setText("- Overbed table      - 2 kursi penunggu  - 2 buah TV ");
                break;
            case 1:
                b = 100000;
                TRAN.setFasilitas("VIP (+100000)");
                KolomFasilitas1.setText("- AC   - 1 Bed   - 1 Kamar mandi   - Bed penunggu   - Kulkas  - Bedside Cabinet   - Kursi tunggu ");
                KolomFasilitas2.setText("- 1 Dispenser   - 1 buah LCD 32   - Lemari Pakaian   - Meja   - Sofa   - Telepon ");
                break;
            case 2:
                b = 200000;
                TRAN.setFasilitas("VVIP (+200000)");
                KolomFasilitas1.setText("- AC   - 1 Bed   - 1 Kamar mandi   - Bedside cabinet   - Kulkas   - Kursi tunggu   - Overbed Table   - Meja TV   - Lemari pakaian ");
                KolomFasilitas2.setText("- Dispenser   - Meja -   Sofabed   - Smart TV 72   - Bed Penunggu    - Telepon    - Ruang keluarga   - 1 set meja makan ");
                break;

        }
    }//GEN-LAST:event_fasilitasActionPerformed

    private void lantai_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lantai_kamarActionPerformed
        switch (lantai_kamar.getSelectedIndex()) {
            case 0:
                status = false;
                TRAN.setLantai_kamar(0);
                break;
            case 1:
                TRAN.setLantai_kamar(1);
                break;
            case 2:
                TRAN.setLantai_kamar(2);
                break;
            case 3:
                TRAN.setLantai_kamar(3);
                break;
            case 4:
                TRAN.setLantai_kamar(4);
                break;
            case 5:
                TRAN.setLantai_kamar(5);
                break;
            case 6:
                TRAN.setLantai_kamar(6);
                break;
            case 7:
                TRAN.setLantai_kamar(7);
                break;
        }
    }//GEN-LAST:event_lantai_kamarActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        this.setVisible(false);
        new HalamanAdmin().setVisible(true);
    }//GEN-LAST:event_kembaliMouseClicked

    private void jenis_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kamarActionPerformed
        switch (jenis_kamar.getSelectedIndex()) {

            case 0:
                TRAN.setJenis_kamar("");
                harga_permalam.setText(null);
                total_harga.setText(null);
                status = false;
                break;

            case 1:
                a = 300000;
                TRAN.setJenis_kamar("Standar");
                harga_permalam.setText("300000");
                break;

            case 2:
                a = 450000;
                TRAN.setJenis_kamar("Supperior");
                harga_permalam.setText("450000");
                break;

            case 3:
                a = 600000;
                TRAN.setJenis_kamar("Deluxe");
                harga_permalam.setText("600000");
                break;

            case 4:
                a = 650000;
                TRAN.setJenis_kamar("Suite");
                harga_permalam.setText("650000");

                break;

            case 5:
                a = 850000;
                TRAN.setJenis_kamar("Presidential Suite");
                harga_permalam.setText("850000");
                break;
        }
    }//GEN-LAST:event_jenis_kamarActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        UPDATE();


    }//GEN-LAST:event_btn_ubahActionPerformed

    private void jumlah_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_hariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_hariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KolomFasilitas1;
    private javax.swing.JLabel KolomFasilitas2;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_total_harga;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> fasilitas;
    private javax.swing.JTextField harga_permalam;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kamar;
    private javax.swing.JTextField jumlah_hari;
    private javax.swing.JLabel kembali;
    private javax.swing.JComboBox<String> lantai_kamar;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tgl_cekin;
    private com.toedter.calendar.JDateChooser tgl_cekout;
    private javax.swing.JLabel titel;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
    public void tampilkanTabel() {
        int row = tabel.getRowCount();
        for (int a = 0; a < row; a++) {
            model.removeRow(0);
        }
        try {
            rs = DB.STATMENT().executeQuery("SELECT * FROM Transaksi");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),
                    rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
