/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel.Admin;


public class HalamanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAdmin
     */
    public HalamanAdmin() {
        initComponents();
        setSize(733, 562);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_CrudAkun = new javax.swing.JButton();
        btn_CrudKamar = new javax.swing.JButton();
        btn_CrudTransaksi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(null);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENU ADMIN");

        btn_CrudAkun.setBackground(new java.awt.Color(255, 255, 255));
        btn_CrudAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CrudAkun.setForeground(new java.awt.Color(255, 51, 102));
        btn_CrudAkun.setText("CRUD Akun User");
        btn_CrudAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrudAkunActionPerformed(evt);
            }
        });

        btn_CrudKamar.setBackground(new java.awt.Color(255, 255, 255));
        btn_CrudKamar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CrudKamar.setForeground(new java.awt.Color(255, 51, 102));
        btn_CrudKamar.setText("CRUD Kamar");
        btn_CrudKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrudKamarActionPerformed(evt);
            }
        });

        btn_CrudTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        btn_CrudTransaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CrudTransaksi.setForeground(new java.awt.Color(255, 51, 102));
        btn_CrudTransaksi.setText("CRUD Transaksi");
        btn_CrudTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrudTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CrudAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CrudKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CrudTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel5)
                .addGap(73, 73, 73)
                .addComponent(btn_CrudAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_CrudKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_CrudTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 520);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Reservasi Hotel");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 110, 271, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/pict/awan.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 10, 460, 124);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/pict/oyo2.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 350, 400, 160);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 0, 520, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrudAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrudAkunActionPerformed
        this.setVisible(false);
        new Hotel.Login.CrudAkun().setVisible(true);
    }//GEN-LAST:event_btn_CrudAkunActionPerformed

    private void btn_CrudKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrudKamarActionPerformed
        this.setVisible(false);
        new Hotel.Menu.CrudKamar().setVisible(true);
    }//GEN-LAST:event_btn_CrudKamarActionPerformed

    private void btn_CrudTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrudTransaksiActionPerformed
        this.setVisible(false);
        new Hotel.Menu.CrudTransaksi().setVisible(true);
    }//GEN-LAST:event_btn_CrudTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrudAkun;
    private javax.swing.JButton btn_CrudKamar;
    private javax.swing.JButton btn_CrudTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
